language: node_js
node_js:
  - 9
  - 8

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - echo "skipping tests"
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release